#baseURL = "https://elk.martinliu.cn"

languageCode = "zh-cn"
DefaultContentLanguage = "zh"
title = "ELK Workshop"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsUseClasses = true
pygmentsCodefences = true

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[Params]

    # Souce Code repository section
    description = "为Elastic技术社区精心打造"
    github_repository = "https://github.com/martinliu/elasticstack-workshop"
    version = "0.1.0"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/martinliu/elasticstack-workshop"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Theme settings section
    dateformat = "2006-01-02" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = ["archives", "blog", "entry", "post", "posts"]


# Global menu section
#[[menu.main]]
#    name = "首页"
#    url = "/"
#    weight = 1

#[[menu.main]]
#    name = "Twitter"
#    url = "https://twitter.com/martinliu"
#    weight = 2
