baseURL = "https://elastic.martinliu.cn/"

languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
title = "Elastic Stack Workshop"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[params]

    # Souce Code repository section
    description = "Elastic 产品技术实践经验总结和解决方案教程"
    github_repository = "https://github.com/martinliu/elasticstack-workshop"
    version = "0.1.0"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/martinliu/elasticstack-workshop"

    # Analytic section
    google_analytics_id = "UA-749876-6" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Open Graph and Twitter Cards settings section
    # Open Graph settings for each page are set on the front matter.
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards
    title = "Elastic Stack Workshop"
    images = ["images/og-image.png"] # Open graph images are placed in `static/images`

    # Theme settings section
    # Theme color
    # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
    custom_font_color = ""
    custom_background_color = "rgb(0,191,179)"

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

    # Date format
    dateformat = "2006-01-02" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
        "workshop",
    ]

    # Algolia site search section
    # See https://www.algolia.com/doc/
    #algolia_search_enable = true
    #algolia_indexName = "hugo-demo-techdoc"
    #algolia_appId = "7W4SAN4PLK"
    #algolia_apiKey = "cbf12a63ff72d9c5dc0c10c195cf9128" # Search-Only API Key

# Global menu section
# See https://gohugo.io/content-management/menus/
[menu]
    [[menu.main]]
        name = "首页"
        url = "/"
        weight = 1

#    [[menu.main]]
#        name = "工作坊"
#        url = "https://twitter.com/thingsym"
#        weight = 2

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false

[outputs]
    home = ["HTML", "RSS"]

ignoreErrors = ["error-remote-getjson"]